### ISSUE TITLE
Can't turn on

### ISSUE THREAD

**Issue by jagajaga** [spwhitt/nix-zsh-completions#1]
Doing as you wrote 
```zsh
fpath=(~/nix-zsh-completions $fpath)
autoload -U compinit && compinit
source ~/nix-zsh-completions/nix.plugin.zsh
```
And nothing works.
Using https://github.com/svenkeidel/nixos-zsh-completion 
```
fpath=(~/nixos-zsh-completion $fpath)
autoload -U compinit && compinit
```
and it works. Ideas?
```bash
> echo $fpath
< ~/nix-zsh-completion etc
```

**Comment by spwhitt** [comment]
You're right that `autoload -U compinit && compinit` is needed, I will add that to the readme. Otherwise, I've just tested it and it is working for me. Two possible thoughts. In the following:

```
> echo $fpath
< ~/nix-zsh-completion etc
```

you're missing the s in `nix-zsh-completions`. Also, a few of the commands, due to the way they're written, require a - to start the completion. For example:

```
nix-build -<TAB>
```

Nothing else comes to mind at the moment. I'll keep thinking :).

**Comment by jagajaga** [comment]
Yup, `s` was missing.
It works now.
Thank you :)

**Comment by jagajaga** [comment]
`nix-env` works nicely.
But
```bash
$ nixos-rebuild
_arguments:comparguments:312: invalid option definition: *--arg[Argument
```

**Comment by spwhitt** [comment]
I'm not sure what would cause that. Are you running zsh from nix-unstable, and if not, can you try that version? Here's my zsh version `zsh 5.0.7`

**Comment by jagajaga** [comment]
```
zsh --version
zsh 5.0.7
```

**Comment by manveru** [comment]
Same issue with zsh 5.1.1

**Comment by manveru** [comment]
@jagajaga @spwhitt 

So after asking someone who actually knows what this crazy completion stuff means, turns out that the `sh_word_split` setopt was causing this particular issue.
He also mentioned that putting the code outside of a .zsh file and inside the completion files would allow the code to be executed without reliance on options set by the user, and therefore should be executed everywhere the same.

For now I disabled my `sh_word_split`, but might be worth doing a little bit of search&replace to make things less DRY and more stable.

**Comment by jagajaga** [comment]
@manveru that worked for me! Thank you.

**Comment by spwhitt** [comment]
Fantastic! Thanks @manveru. I'm admittedly new to writing ZSH completions, and I certainly would have never figured this one out. When I get a free moment within the next week or so I'll figure out how to refactor to avoid the problem (make it less DRY like you suggested if necessary), though if someone else wants to make a pull request I'll happily merge it instead and save myself the work.
